### ISSUE TITLE
After jade update, the server crashes on rendering

### ISSUE THREAD

**Issue by fodor0205** [1602/jade-ext#7]
After updating jade to the newest version available on npm, the server crashes when the code calls the `render()` function

My jade template compiles well with the previous version.

`npm list` output:

```
$ npm list
├─┬ jade@0.31.1
│ ├── character-parser@1.0.2
│ ├─┬ commander@1.1.1
│ │ └── keypress@0.1.0
│ ├── mkdirp@0.3.5
│ ├─┬ monocle@0.1.48
│ │ └─┬ readdirp@0.2.4
│ │   └─┬ minimatch@0.2.12
│ │     ├── lru-cache@2.3.0
│ │     └── sigmund@1.0.0
│ ├─┬ transformers@2.0.1
│ │ ├─┬ css@1.0.8
│ │ │ ├── css-parse@1.0.4
│ │ │ └── css-stringify@1.0.5
│ │ ├─┬ promise@2.0.0
│ │ │ └── is-promise@1.0.0
│ │ └─┬ uglify-js@2.2.5
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.2
│ │   └─┬ source-map@0.1.22
│ │     └── amdefine@0.0.5
│ └─┬ with@1.0.4
│   └─┬ lexical-scope@0.0.12
│     └─┬ astw@0.0.0
│       └── esprima@1.0.2
├── jade-ext@0.0.7-9
```

Error stacktrace:

```
Rendering user/show using layout site_layout
TypeError: /home/user/wwwroot/project/app/views/user/show.jade:1
  > 1| #user
    2|   .alert.alert-info
    3|     | #{currentUser.name}
    4|   .row-fluid

Cannot read property 'callee' of undefined
    at eval (eval at <anonymous> (/home/user/wwwroot/project/node_modules/jade/lib/jade.js:170:8), <anonymous>:5:231)
    at /home/user/wwwroot/project/node_modules/jade/lib/jade.js:171:35
    at Object.exports.render (/home/user/wwwroot/project/node_modules/jade/lib/jade.js:205:14)
    at View.exports.renderFile [as engine] (/home/user/wwwroot/project/node_modules/jade/lib/jade.js:232:13)
    at View.render (/home/user/wwwroot/project/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/home/user/wwwroot/project/node_modules/express/lib/application.js:506:10)
    at ServerResponse.res.render (/home/user/wwwroot/project/node_modules/express/lib/response.js:756:7)
    at Controller.renderView (/home/user/wwwroot/project/node_modules/compound/lib/controller-extensions.js:134:18)
    at Controller.render (/home/user/wwwroot/project/node_modules/compound/lib/controller-extensions.js:79:10)
    at Object.show (eval at <anonymous> (/home/user/wwwroot/project/node_modules/compound/node_modules/kontroller/lib/base.js:157:17), <anonymous>:9:10)
    at Array.6 (/home/user/wwwroot/project/node_modules/compound/node_modules/kontroller/lib/flow-control.js:150:28)
    at ActionContext.run [as innerNext] (/home/user/wwwroot/project/node_modules/compound/node_modules/kontroller/lib/flow-control.js:103:31)
    at Controller.BaseController.next (/home/user/wwwroot/project/node_modules/compound/node_modules/kontroller/lib/base.js:107:22)
    at eval (eval at <anonymous> (/home/user/wwwroot/project/node_modules/compound/node_modules/kontroller/lib/base.js:157:17), <anonymous>:50:5)
    at _fulfilled (/home/user/wwwroot/project/node_modules/q/q.js:981:54)
    at resolvedValue.promiseDispatch.done (/home/user/wwwroot/project/node_modules/q/q.js:1011:30)
    at makePromise.promise.promiseDispatch (/home/user/wwwroot/project/node_modules/q/q.js:610:13)
    at Object._onImmediate (/home/user/wwwroot/project/node_modules/q/q.js:489:41)
    at processImmediate [as _immediateCallback] (timers.js:317:15)
```

**Comment by 1602** [comment]
Any helpers using 'callee' are deprecated, for example instead `formFor(resource, function(form) {...});` now blockless version should be used: var form = formFor(resource); form.begin(); form.end();

**Comment by fodor0205** [comment]
I don't use any of the deprecated functions.
I've checked the compound repository:
`formTag`, `fieldsFor` and `formFor` are the 3 helpers using it, and I don't use any of them for sure.

I assume the problem is caused by this line, at least I haven't found any other reference to `callee`:
https://github.com/1602/jade-ext/blob/a7d247481fad6082f400efd07725348cfd93865f/index.js#L8

@1602  Could you please have a look at that code?
